manta_facturation_detalle:
    resource: "@MantaFacturationBundle/Controller/DetalleController.php"
    type:     annotation

manta_facturation_factura:
    resource: "@MantaFacturationBundle/Controller/FacturaController.php"
    type:     annotation

manta_facturation_cliente:
    resource: "@MantaFacturationBundle/Controller/ClienteController.php"
    type:     annotation

manta_facturation_producto:
    resource: "@MantaFacturationBundle/Controller/ProductoController.php"
    type:     annotation

manta_facturation_categoria:
    resource: "@MantaFacturationBundle/Controller/CategoriaController.php"
    type:     annotation

manta_facturation:
    resource: "@MantaFacturationBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
