<?php

namespace Manta\FacturationBundle\Repository;

/**
 * DetalleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetalleRepository extends \Doctrine\ORM\EntityRepository
{
}
